CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY '12sabari';
GRANT ALL PRIVILEGES ON sybiosis.* TO 'admin'@'%';
FLUSH PRIVILEGES;

USE sybiosis;

CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  age INT(3) NOT NULL,
  email VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);
