apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: YWRtaW4=        # username in base64 
  password: MTJzYWJhcmk=    # pwd in base64
  dbname: c3liaW9zaXM=      # dbname in base64
